# Generated by Django 4.1.3 on 2022-12-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_events', '0002_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
